site_name: School of DevOps
site_url: https://moabukar.github.io/school-of-devops/
site_author: Mohamed Abukar
repo_url: https://github.com/moabukar/school-of-devops
dev_addr: "127.0.0.1:8000"
docs_dir: docs
theme: 
  name: material
  # custom_dir: overrides
  extra_css:
    - stylesheets/custom.css

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: dark_blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

nav:
- Home: index.md
- Level 1 - Fundamentals:
    - Linux:
        - Linux Intro: level1/linux/linux1.md
        - Linux CLI: level1/linux/linux2.md
    - Git:
        - Git Basics: level1/git/git-basics.md
        - Working With Branches: level1/git/branches.md
        - Github and Hooks: level1/git/github-hooks.md
        - Conclusion: level1/git/conclusion.md
    - Linux Networking:
        - Introduction: level1/networking/networking1.md
    - AWS:
        - Introduction: level1/aws/intro.md
        - Compute: level1/aws/compute.md


- Level 2:
    - Terraform:
        - Terraform plan: level2/terraform/plan.md
        - Terraform intro: level2/terraform/intro.md
    - Docker:
        - Docker basics: level2/docker/intro.md
    - CICD:
        - Terraform basics: level2/cicd/intro.md
    - Kubernetes:
        - K8s basics: level2/k8s/intro.md


- Contribute: CONTRIBUTING.md
- Code of Conduct: CODE_OF_CONDUCT.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  

copyright: |
  &copy; 2023 <a href="https://github.com/moabukar"  target="_blank" rel="noopener">Mohamed Abukar</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/moabukar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moabukar_1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moabukar/